name: 채점
run-name: Python 으로 채점

on:
  push:
    branches: main

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: 브랜치 가져오기
        uses: actions/checkout@v4
      
      - name: 파이썬 설치
        uses: actions/setup-python@v5
        with: 
          python-version: '3.11'
        
      - name: 채점 스크립트 권한 추가
        run: chmod +x ./grade.sh
      
      - name: 파이썬 채점 시작
        run: ./grade.sh
